version: "3.9"

services:
  line-and-discord:
    image: a3510377/line-and-discord:linux-arm64
    restart: unless-stopped
    expose:
      - 5000
    volumes:
      - /servers/config/line-and-discord/data:/app/data
    environment:
      LINE_BOT_ACCESS_TOKEN: ${LINE_BOT_ACCESS_TOKEN}
      LINE_BOT_SECRET: ${LINE_BOT_SECRET}
      DISCORD_TOKEN: ${DISCORD_TOKEN}

  ngrok:
    image: a3510377/node-ngrok:linux-arm64
    restart: unless-stopped
    expose:
      - 1333
    environment:
      REGION: jp
      PROTO: http
      HOST: line-and-discord:5000
      AUTH_TOKEN: ${NGROK_AUTHTOKEN}
