version: "3.9"

services:
  line-and-discord:
    image: ghcr.io/a3510377/line-and-discord:latest
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    depends_on:
      - ngrok
    expose:
      - 5000
    volumes:
      - /servers/config/line-and-discord/data:/app/data
    environment:
      LINE_BOT_ACCESS_TOKEN: ${LINE_BOT_ACCESS_TOKEN}
      LINE_BOT_SECRET: ${LINE_BOT_SECRET}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      NGROK: true

  ngrok:
    image: ghcr.io/a3510377/node-ngrok:latest
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
    expose:
      - 1333
    environment:
      REGION: jp
      PROTO: http
      HOST: line-and-discord:5000
      AUTH_TOKEN: ${NGROK_AUTHTOKEN}
